/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.12.2
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client';
    


// Services

export interface PeerServiceDef {
    peers: (callParams: CallParams$$<null>) => string[] | Promise<string[]>;
}
export function registerPeerService(service: PeerServiceDef): void;
export function registerPeerService(serviceId: string, service: PeerServiceDef): void;
export function registerPeerService(peer: IFluenceClient$$, service: PeerServiceDef): void;
export function registerPeerService(peer: IFluenceClient$$, serviceId: string, service: PeerServiceDef): void;
       

export function registerPeerService(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "peerService",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "peers" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "array",
                            "type" : {
                                "tag" : "scalar",
                                "name" : "string"
                            }
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      


export interface TimeAmuletDef {
    tick: (callParams: CallParams$$<null>) => void | Promise<void>;
}
export function registerTimeAmulet(service: TimeAmuletDef): void;
export function registerTimeAmulet(serviceId: string, service: TimeAmuletDef): void;
export function registerTimeAmulet(peer: IFluenceClient$$, service: TimeAmuletDef): void;
export function registerTimeAmulet(peer: IFluenceClient$$, serviceId: string, service: TimeAmuletDef): void;
       

export function registerTimeAmulet(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "timeAmulet",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "tick" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "nil"
                }
            }
        }
    }
}
    );
}
      
// Functions
export const getLogs_script = `
                    (seq
                     (seq
                      (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                      (xor
                       (new $results
                        (seq
                         (seq
                          (seq
                           (seq
                            (seq
                             (seq
                              (new $option-inline
                               (seq
                                (seq
                                 (seq
                                  (new $array-inline
                                   (seq
                                    (seq
                                     (seq
                                      (seq
                                       (seq
                                        (seq
                                         (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWFbasz6SnGxhPq3KWn8KgNW4asNKskxR5JizMdszM4KCN" "spellId" "e6ce8cea-d53b-4b39-bdf1-574c62c84135" "workerId" "12D3KooWHa8utF8tEkGW6N9hPwv6mUk8DkWfTs7tNVZQN7JJ4roU"] SpellLocation_obj)
                                         (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWBCAWAGNMfqaBG1kUv49dkK8wSNeiTfGubLLjGQaFBf6z" "spellId" "a88fe196-ff6a-42e7-9fa6-eecf4539c1f4" "workerId" "12D3KooWEA2r82M7SguMJnmemrcn7szR2vdXN56zpWEePbmNarhH"] SpellLocation_obj-0)
                                        )
                                        (call %init_peer_id% ("json" "obj") ["hostId" "12D3KooWEqbHHE1bzk1nJ8LE2Wbm2UaycYjRsSB4CTxDS342Boip" "spellId" "e9f6440e-2e3b-4c2c-a575-677d5e3c71ce" "workerId" "12D3KooWShExGN2YgnrPyouA2xU8v2BVds6aK2xWjHxCUjP3znn6"] SpellLocation_obj-1)
                                       )
                                       (ap SpellLocation_obj $array-inline)
                                      )
                                      (ap SpellLocation_obj-0 $array-inline)
                                     )
                                     (ap SpellLocation_obj-1 $array-inline)
                                    )
                                    (canon %init_peer_id% $array-inline  #array-inline-0)
                                   )
                                  )
                                  (call %init_peer_id% ("json" "obj") ["definition" "bafkreigjebk7hweu37mma4lg4kgcl6ih4f7xzhqkldsmvmahdyevi72abm" "dummyDealId" "defaultWorker_12D3KooWNe8E9vzJvYPn6k8TUAiGxCQDX57oEgPJs9fVnQq6NCv2_4545008786066116" "installationSpells" #array-inline-0 "relayId" "12D3KooWFbasz6SnGxhPq3KWn8KgNW4asNKskxR5JizMdszM4KCN" "timestamp" "2023-11-16T11:58:10.549Z"] Host_obj)
                                 )
                                 (xor
                                  (ap Host_obj $option-inline)
                                  (null)
                                 )
                                )
                                (canon %init_peer_id% $option-inline  #option-inline-0)
                               )
                              )
                              (call %init_peer_id% ("json" "obj") ["defaultWorker" #option-inline-0] Hosts_obj)
                             )
                             (ap Hosts_obj.$.defaultWorker Hosts_obj_flat)
                            )
                            (ap Hosts_obj_flat.$.[0].installationSpells Hosts_obj_flat_flat)
                           )
                           (fold Hosts_obj_flat_flat w-0
                            (seq
                             (xor
                              (seq
                               (seq
                                (seq
                                 (seq
                                  (seq
                                   (new $-ephemeral-stream-
                                    (new #-ephemeral-canon-
                                     (canon -relay- $-ephemeral-stream-  #-ephemeral-canon-)
                                    )
                                   )
                                   (new $-ephemeral-stream-
                                    (new #-ephemeral-canon-
                                     (canon w-0.$.hostId $-ephemeral-stream-  #-ephemeral-canon-)
                                    )
                                   )
                                  )
                                  (call w-0.$.workerId ("worker-spell" "list_get_strings") ["logs"] ret)
                                 )
                                 (ap ret $results)
                                )
                                (new $-ephemeral-stream-
                                 (new #-ephemeral-canon-
                                  (canon w-0.$.hostId $-ephemeral-stream-  #-ephemeral-canon-)
                                 )
                                )
                               )
                               (new $-ephemeral-stream-
                                (new #-ephemeral-canon-
                                 (canon -relay- $-ephemeral-stream-  #-ephemeral-canon-)
                                )
                               )
                              )
                              (seq
                               (seq
                                (seq
                                 (new $-ephemeral-stream-
                                  (new #-ephemeral-canon-
                                   (canon w-0.$.hostId $-ephemeral-stream-  #-ephemeral-canon-)
                                  )
                                 )
                                 (new $-ephemeral-stream-
                                  (new #-ephemeral-canon-
                                   (canon -relay- $-ephemeral-stream-  #-ephemeral-canon-)
                                  )
                                 )
                                )
                                (new $-ephemeral-stream-
                                 (new #-ephemeral-canon-
                                  (canon %init_peer_id% $-ephemeral-stream-  #-ephemeral-canon-)
                                 )
                                )
                               )
                               (fail %last_error%)
                              )
                             )
                             (next w-0)
                            )
                           )
                          )
                          (canon %init_peer_id% $results  #-results-fix-0)
                         )
                         (ap #-results-fix-0 -results-flat-0)
                        )
                       )
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 0])
                      )
                     )
                     (call %init_peer_id% ("callbackSrv" "response") [-results-flat-0])
                    )
    `
 

export function getLogs(
    config?: {ttl?: number}
): Promise<{ error: string; strings: string[]; success: boolean; }[]>;

export function getLogs(
    peer: IFluenceClient$$,
    config?: {ttl?: number}
): Promise<{ error: string; strings: string[]; success: boolean; }[]>;

export function getLogs(...args: any) {


    return callFunction$$(
        args,
        {
    "functionName" : "getLogs",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "array",
                    "type" : {
                        "tag" : "struct",
                        "name" : "StringListValue",
                        "fields" : {
                            "error" : {
                                "tag" : "scalar",
                                "name" : "string"
                            },
                            "strings" : {
                                "tag" : "array",
                                "type" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            },
                            "success" : {
                                "tag" : "scalar",
                                "name" : "bool"
                            }
                        }
                    }
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        getLogs_script
    )
}

/* eslint-enable */