/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.12.2
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client';
    


// Services

export interface TimeAmuletDef {
    tick: (callParams: CallParams$$<null>) => void | Promise<void>;
}
export function registerTimeAmulet(service: TimeAmuletDef): void;
export function registerTimeAmulet(serviceId: string, service: TimeAmuletDef): void;
export function registerTimeAmulet(peer: IFluenceClient$$, service: TimeAmuletDef): void;
export function registerTimeAmulet(peer: IFluenceClient$$, serviceId: string, service: TimeAmuletDef): void;
       

export function registerTimeAmulet(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "timeAmulet",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "tick" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "nil"
                }
            }
        }
    }
}
    );
}
      
// Functions


/* eslint-enable */